image: caixin0823/laravel-docker
      
deploy-testing:
  stage: deploy
  script:
    - ssh $SERVER_TOKEN_TEST -t "cd ${WEB_ROOT}${CI_PROJECT_NAME} && git pull && sh deploy.sh"
  only:
    - dev
  tags:
    - blockchain
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_TEST" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod -R 600 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS_TEST" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
